USE [master]
GO

/****** Object:  Database [InventoryDB]    Script Date: 4/3/2021 4:27:16 AM ******/
CREATE DATABASE [InventoryDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'InventoryDB', FILENAME = N'C:\Users\arpitha.s\InventoryDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'InventoryDB_log', FILENAME = N'C:\Users\arpitha.s\InventoryDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [InventoryDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [InventoryDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [InventoryDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [InventoryDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [InventoryDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [InventoryDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [InventoryDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [InventoryDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [InventoryDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [InventoryDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [InventoryDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [InventoryDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [InventoryDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [InventoryDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [InventoryDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [InventoryDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [InventoryDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [InventoryDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [InventoryDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [InventoryDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [InventoryDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [InventoryDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [InventoryDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [InventoryDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [InventoryDB] SET  MULTI_USER 
GO

ALTER DATABASE [InventoryDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [InventoryDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [InventoryDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [InventoryDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [InventoryDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [InventoryDB] SET QUERY_STORE = OFF
GO

USE [InventoryDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [InventoryDB] SET  READ_WRITE 
GO

